[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
# The primary colors for the terminal window
background = '#121f29'
foreground = '#dcdcdc'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.normal]
# Normal colors used by applications
black = '#1e2b36'
red = '#a66a6a'
green = '#698b69'
yellow = '#b68d4c'
blue = '#4b7086'
magenta = '#8c6c8c'
cyan = '#7191a1'
white = '#c0c0c0'

[colors.bright]
# Bright colors used for emphasis
black = '#293d4d'
red = '#d27b7b'
green = '#7da47d'
yellow = '#e1b36f'
blue = '#6b8ea2'
magenta = '#ab8fab'
cyan = '#8fb3c5'
white = '#ffffff'
